name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: List files in workspace
      run: ls -R .

    - name: Install dependencies
      run: |
        echo "Attempting to display requirements file:"
        cat requirements/dev.txt
        echo "--- End of requirements file ---"
        python -m pip install --upgrade pip
        echo "Attempting to install dependencies using absolute path:"
        pip install -r ${{ github.workspace }}/requirements/dev.txt


    - name: Run tests with coverage
      run: pytest --cov=src tests/